# Query Evaluation From Result Files

This notebook reads `executions_*.csv` files from one summary run folder and evaluates each response against ground truth using a configurable evaluator model.

It does not import or use `model_evaluation.py`.

In [ ]:
from query_utils import evaluate_summary_folder

# Path with model execution files (executions_*.csv)
SUMMARY_RUN_DIR = "../outputs/summary/archive_04-2026_to_06-2026/20260417_201301 E1 (keep)"

# Evaluator model and runtime configuration
EVALUATOR_MODEL = "mistral:7b"
OLLAMA_SERVER = "http://156.35.95.33:11434"
EVALUATOR_OPTIONS = {
    "temperature": 0.05,
}
EVALUATOR_THINKING = False

# Quick test mode: run only selected queries and one source model.
TEST_MODE = True
TEST_QUERY_IDS = ["Q01"]
TEST_MODEL = "deepseek-r1:8b"

# Output folder for evaluation artifacts
OUTPUT_ROOT = "outputs/query_eval"

# Optional JSON file with ground truths by query id.
# If None, defaults from query_utils.DEFAULT_GROUND_TRUTHS are used.
GROUND_TRUTHS_FILE = "ground_truths_default.json"

# Criterion-specific query sets (must be non-empty for each defined criterion).
CRITERION_1_QUERY_IDS = ["Q01", "Q02", "Q03", "Q04", "Q05"]
CRITERION_2_QUERY_IDS = ["Q01", "Q02", "Q03", "Q04", "Q05"]
CRITERION_3_QUERY_IDS = ["Q01", "Q02", "Q03", "Q04", "Q05"]
CRITERION_4_QUERY_IDS = ["Q01", "Q02", "Q03", "Q04", "Q05"]
CRITERION_5_QUERY_IDS = ["Q01", "Q02", "Q03", "Q04", "Q05"]
CRITERION_6_QUERY_IDS = ["Q01", "Q02", "Q03", "Q04", "Q05"]

PROMPTS_DIR = "prompts"

CRITERIA_CONFIG = {
    "A1_CS": {
        "name": "Syntactic Correctness (Well-formedness)",
        "weight": 1 / 6,
        "query_ids": CRITERION_1_QUERY_IDS,
        "prompt_file": f"{PROMPTS_DIR}/A1_CS.txt",
    },
    "A2_FS": {
        "name": "Semantic Faithfulness",
        "weight": 1 / 6,
        "query_ids": CRITERION_2_QUERY_IDS,
        "prompt_file": f"{PROMPTS_DIR}/A2_FS.txt",
    },
    "A3_SQ": {
        "name": "Structural Quality",
        "weight": 1 / 6,
        "query_ids": CRITERION_3_QUERY_IDS,
        "prompt_file": f"{PROMPTS_DIR}/A3_SQ.txt",
    },
    "A4_HQ": {
        "name": "Hypothesis Quality",
        "weight": 1 / 6,
        "query_ids": CRITERION_4_QUERY_IDS,
        "prompt_file": f"{PROMPTS_DIR}/A4_HQ.txt",
    },
    "A5_MR": {
        "name": "Minimality and Non-redundancy",
        "weight": 1 / 6,
        "query_ids": CRITERION_5_QUERY_IDS,
        "prompt_file": f"{PROMPTS_DIR}/A5_MR.txt",
    },
    "A6_AP": {
        "name": "Aggregation and Projection Correctness",
        "weight": 1 / 6,
        "query_ids": CRITERION_6_QUERY_IDS,
        "prompt_file": f"{PROMPTS_DIR}/A6_AP.txt",
    },
}

In [ ]:
result = evaluate_summary_folder(
    summary_root=SUMMARY_RUN_DIR,
    evaluator_model=EVALUATOR_MODEL,
    ollama_server=OLLAMA_SERVER,
    output_root=OUTPUT_ROOT,
    evaluator_options=EVALUATOR_OPTIONS,
    evaluator_thinking=EVALUATOR_THINKING,
    criteria_config=CRITERIA_CONFIG,
    ground_truths_path=GROUND_TRUTHS_FILE,
    test_query_ids=TEST_QUERY_IDS if TEST_MODE else None,
    test_model=TEST_MODEL if TEST_MODE else None,
)

print("Output folder:", result["output_dir"])
print("All rows file:", result["all_rows_file"])
print("Model/mode/query by criterion:", result["model_mode_query_criterion_file"])
print("Model/mode by criterion:", result["model_mode_criterion_file"])
print("Query by criterion:", result["query_criterion_file"])
print("Model/mode/query summary:", result["model_mode_query_file"])
print("Model/mode overall:", result["model_mode_file"])
print("Query overall:", result["query_file"])

Starting source model: mistral_7b | Evaluator: gemma4:e4b
  - [1/5] Evaluating executions_mistral_7b_Q01_Give_me_the_films_directed_by_Eastwood_a_thinking_false_20260417_201301.csv
  - [2/5] Evaluating executions_mistral_7b_Q02_Give_me_the_films_whose_actors_won_an_Os_thinking_false_20260417_201301.csv
  - [3/5] Evaluating executions_mistral_7b_Q03_Give_me_the_films_featuring_more_than_th_thinking_false_20260417_201301.csv
  - [4/5] Evaluating executions_mistral_7b_Q04_Give_me_the_films_whose_directors_have_t_thinking_false_20260417_201301.csv
  - [5/5] Evaluating executions_mistral_7b_Q05_Give_me_the_films_in_which_all_the_actor_thinking_false_20260417_201301.csv
Saved output folder: outputs\query_eval\20260420_125130
Output folder: outputs\query_eval\20260420_125130
All rows file: outputs\query_eval\20260420_125130\evaluation_all_runs_20260420_125130.csv
Model/mode/query summary: outputs\query_eval\20260420_125130\evaluation_model_mode_query_20260420_125130.csv
Model/mode overall: outputs\query_eval\20260420_125130\evaluation_model_mode_overall_20260420_125130.csv
Query overall: outputs\query_eval\20260420_125130\evaluation_query_overall_20260420_125130.csv

In [ ]:
# Per-model-mode by criterion
display(result["model_mode_criterion_df"])

,Model,Thinking,Total_Runs,Overall_Score,Std_Score,95% CI (Score),Min_Score,Max_Score,Queries_Evaluated
0,mistral:7b,False,30,0.3,0.4418,"[0.0000, 1.0000]",0.0,1.0,1

In [ ]:
# Per-query by criterion
display(result["query_criterion_df"])

,Query ID,Total_Runs,Overall_Score,Std_Score,95% CI (Score),Min_Score,Max_Score,Models_Evaluated
0,Q04,30,0.3,0.4418,"[0.0000, 1.0000]",0.0,1.0,1

In [ ]:
# Per-model-mode-query by criterion
display(result["model_mode_query_criterion_df"])

,Model,Thinking,Query ID,Runs,Mean_Score,Std_Score,95% CI (Score),Min_Score,Max_Score,Avg_Inference_Time_s
0,mistral:7b,False,Q04,30,0.3,0.4418,"[0.0000, 1.0000]",0.0,1.0,5.0243

In [ ]:
# Per-model-mode overall summary (with Aspect_1..Aspect_6 + Weighted_Overall)
display(result["model_mode_df"])

In [ ]:
# Per-query overall summary (with Aspect_1..Aspect_6 + Weighted_Overall)
display(result["query_df"])

In [ ]:
# Per-model-mode-query overall summary (with Aspect_1..Aspect_6 + Weighted_Overall)
display(result["model_mode_query_df"])